# Azure DevOps Pipeline

name: $(Date:yyyyMMdd)$(Rev:r)

variables:
  vmImage: 'ubuntu-latest'
  dockerImageName: 'orneholmcognitivejukeboxweb'
  dockerImageTag: $(Build.BuildNumber)

trigger:
- master

stages:
- stage: BuildWebImage
  displayName:  'Build web image'
  dependsOn: []
  jobs:
  - job: BuildWebImage
    displayName: 'Build'

    pool:
      vmImage: '$(vmImage)'

    variables:
      pathToPublishProjects: '**/src/**/*.*sproj'

    steps:

    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: acrDockerRegistryServiceConnection
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: dockerHubDockerRegistryServiceConnection
    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: buildAndPush
        buildContext: ''
        repository: peterorneholm/orneholmcognitivejukeboxweb
        Dockerfile: src/Orneholm.CognitiveJukebox.Web/Dockerfile
        tags: |
          $(dockerImageTag)
          latest

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: '$(artifactName)'
